services:
  - type: web
    name: iv1201-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DATABASE_URL
        fromDatabase:
          name: amusementparkjp
          username: jp1201
          property: internalConnectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

  - type: web
    name: iv1201-frontend
    env: static
    plan: free
    rootDir: frontend/web-app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    nodeVersion: 24.13.0
    envVars:
      - key: VITE_API_BASE_URL
        value: https://amusementparkjp.onrender.com/

  - type: pserv
    name: amusementparkjp
    username: jp1201
    env: postgres
    plan: free
    ipAllowList: []
