services:
  - type: web
    name: iv1201-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DATABASE_URL
        fromDatabase:
          name: iv1201-postgres
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

  - type: pserv
    name: iv1201-postgres
    env: postgres
    plan: free
    ipAllowList: []
